apiVersion: v1
kind: Service
metadata:
  name: server-manager-service
  namespace: fedops
spec:
  selector:
    run: fl-server-st
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
